### ISSUE TITLE
sipcapture/webapp latest docker:image brocken. No configuration file loaded:  While parsing config: invalid character '}' looking for beginning of object key string

### ISSUE THREAD

**Issue by khorsmann** [sipcapture/homer7-docker#76]
Hi,
i tried latest version in master and in 7.7 branch. The sipcapture/webapp is broken. Unfortuanly the sipcapture/webapp container is not tagged - only latest.

```
sipcapture/webapp 1c559f8d4b3

docker-compose version 1.23.2, build 1110ad01
Docker version 19.03.8, build afacb8b

lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.7.1908 (Core)
Release:        7.7.1908
Codename:       Core

sipcapture/webapp 1c559f8d4b3
docker image ls sipcapture/webapp
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
sipcapture/webapp   latest              51c559f8d4b3        12 hours ago        30.4MB
sipcapture/webapp   <none>              7b4dc804a767        2 weeks ago         30.8MB
sipcapture/webapp   <none>              bdfff81dfb50        6 weeks ago         30.7MB

homer-webapp      | Pre-Flight provisioning completed!
homer-webapp      | No configuration file loaded:  While parsing config: invalid character '}' looking for beginning of object key string
homer-webapp      | time="2020-05-18T10:13:01Z" level=error msg="No configuration file loaded - using defaults"
homer-webapp      | panic: DB configuration file not found:
homer-webapp      |
homer-webapp      | goroutine 1 [running]:
homer-webapp      | main.readConfig()
homer-webapp      |     /homer-app/main.go:843 +0x303
homer-webapp      | main.main()
homer-webapp      |     /homer-app/main.go:191 +0x41
homer-webapp      | No configuration file loaded:  While parsing config: invalid character '}' looking for beginning of object key string
homer-webapp      | time="2020-05-18T10:13:01Z" level=error msg="No configuration file loaded - using defaults"
homer-webapp      | panic: DB configuration file not found:
homer-webapp      |
homer-webapp      | goroutine 1 [running]:
homer-webapp      | main.readConfig()
homer-webapp      |     /homer-app/main.go:843 +0x303
homer-webapp      | main.main()
homer-webapp      |     /homer-app/main.go:191 +0x41
grafana           | t=2020-05-18T10:13:02+0000 lvl=warn msg="Skipping OAuth auto login because multiple OAuth providers are configured"
homer-webapp      | time="2020-05-18T10:13:02Z" level=error msg="No configuration file loaded - using defaults"
homer-webapp      | No configuration file loaded:  While parsing config: invalid character '}' looking for beginning of object key string
homer-webapp      | panic: DB configuration file not found:
homer-webapp      |
homer-webapp      | goroutine 1 [running]:
homer-webapp      | main.readConfig()
homer-webapp      |     /homer-app/main.go:843 +0x303
homer-webapp      | main.main()
homer-webapp      |     /homer-app/main.go:191 +0x41
homer-webapp      | time="2020-05-18T10:13:02Z" level=error msg="No configuration file loaded - using defaults"
homer-webapp      | No configuration file loaded:  While parsing config: invalid character '}' looking for beginning of object key string
homer-webapp      | panic: DB configuration file not found:
homer-webapp      |
homer-webapp      | goroutine 1 [running]:
homer-webapp      | main.readConfig()
homer-webapp      |     /homer-app/main.go:843 +0x303
homer-webapp      | main.main()
homer-webapp      |     /homer-app/main.go:191 +0x41
homer-webapp      | Database provisioning completed!
homer-webapp      | time="2020-05-18T10:13:02Z" level=error msg="No configuration file loaded - using defaults"
homer-webapp      | No configuration file loaded:  While parsing config: invalid character '}' looking for beginning of object key string
homer-webapp      | panic: DB configuration file not found:
homer-webapp      |
homer-webapp      | goroutine 1 [running]:
homer-webapp      | main.readConfig()
homer-webapp      |     /homer-app/main.go:843 +0x303
homer-webapp      | main.main()
homer-webapp      |     /homer-app/main.go:191 +0x41

```

**Comment by lmangani** [comment]
yeah sorry we merged an issue my mistake - rebuilding containers now hopefully solving it!

**Comment by khorsmann** [comment]
Thank you Lorenzo.

Works now. Found another bug ;-) but not with the docker image. More with the app.
Testet this image. 

```
[root@homer1.a.office.4com.de ~]# docker image ls sipcapture/webapp                                                                                                                            REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE                                                                                                           sipcapture/webapp   latest              fe3a3a1d20af        3 hours ago         30.4MB
--

```
